In [1]:
import torch
from torch.nn import Parameter
from torch_scatter import scatter_add
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import add_self_loops

### 1. Create an example of graphical data with pyg

In [2]:
# Initiate a torch.tensor called edge_index
edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)

In [3]:
# initiate a torch.tensor called x to be the feature tensor of nodes
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

#### print it out

In [4]:
print(edge_index)

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])


In [5]:
# size() method
print(edge_index.size())
print(x.size())

torch.Size([2, 4])
torch.Size([3, 1])


In [6]:
print("This is the number of directed edge: "+ str(edge_index.size(1)))

This is the number of directed edge: 4


In [7]:
print("This is the device of edge_index: "+ str(edge_index.device))

This is the device of edge_index: cpu


In [8]:
edge_weight = torch.ones((edge_index.size(1), ), dtype=None, device=edge_index.device)

In [9]:
edge_weight

tensor([1., 1., 1., 1.])

In [10]:
edge_index.new_zeros(x.size(0))

tensor([0, 0, 0])

**new_zeros(size)**:

Returns a Tensor of size size filled with 0. By default, the returned Tensor has the same torch.dtype and torch.device as this tensor.

### TUDataset - 'DD'


In [11]:
from torch_geometric.datasets import TUDataset
import os

In [12]:
TUDataset(os.path.join('data','DD'),name='DD')

DD(1178)

In [13]:
dataset = TUDataset(os.path.join('data','DD'),name='DD')

In [14]:
dataset.num_classes

2

In [15]:
dataset.num_features

89

In [16]:
len(dataset)

1178

In [17]:
data = dataset.data

c:\Users\Paul\anaconda3\Lib\site-packages\torch_geometric\data\in_memory_dataset.py:284: UserWarning: It is not recommended to directly access the internal storage format `data` of an 'InMemoryDataset'. The data of the dataset is already cached, so any modifications to `data` will not be reflected when accessing its elements. Clearing the cache now by removing all elements in `dataset._data_list`. If you are absolutely certain what you are doing, access the internal storage via `InMemoryDataset._data` instead to suppress this warning. Alternatively, you can access stacked individual attributes of every graph via `dataset.{attr_name}`.
  warnings.warn(msg)


In [21]:
data.edge_index

tensor([[  0,   0,   0,  ..., 170, 170, 170],
        [  1,   2,   3,  ..., 149, 168, 169]])

### Test SAGPool (use gnn venv)

In [1]:
from torch_geometric.nn import GCNConv
from torch_geometric.nn.pool.topk_pool import topk,filter_adj
from torch.nn import Parameter
import torch

In [ ]:
in_channels = 128

score_layer = GCNConv(in_channels,1)