In [1]:
import torch
from torch.nn import Parameter
from torch_scatter import scatter_add
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import add_self_loops

### 1. Create an example of graphical data with pyg

In [2]:
# Initiate a torch.tensor called edge_index
edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]], dtype=torch.long)

In [13]:
# initiate a torch.tensor called x to be the feature tensor of nodes
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

#### print it out

In [3]:
print(edge_index)

tensor([[0, 1, 1, 2],
        [1, 0, 2, 1]])


In [15]:
# size() method
print(edge_index.size())
print(x.size())

torch.Size([2, 4])
torch.Size([3, 1])


In [8]:
print("This is the number of directed edge: "+ str(edge_index.size(1)))

This is the number of directed edge: 4


In [10]:
print("This is the device of edge_index: "+ str(edge_index.device))

This is the device of edge_index: cpu


In [11]:
edge_weight = torch.ones((edge_index.size(1), ), dtype=None, device=edge_index.device)

In [12]:
edge_weight

tensor([1., 1., 1., 1.])

In [23]:
edge_index.new_zeros(x.size(0))

tensor([0, 0, 0])

**new_zeros(size)**:

Returns a Tensor of size size filled with 0. By default, the returned Tensor has the same torch.dtype and torch.device as this tensor.